version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    assignees:
      - 't28hub'
    commit-message:
      prefix: 'chore(deps)'
      include: 'scope'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 't28hub'
    commit-message:
        prefix: 'chore(ci)'
        include: 'scope'
