branches:
  - 'main'
ci: true
tagFormat: v${version}

plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: 'conventionalcommits'
      releaseRules:
        - breaking: true
          release: 'major'
        - type: 'feat'
          release: 'minor'
        - revert: true
          release: 'patch'
        - type: 'build'
          release: 'patch'
        - type: 'chore'
          release: 'patch'
        - type: 'fix'
          release: 'patch'
        - type: 'perf'
          release: 'patch'
        - type: 'refactor'
          release: 'patch'
        - type: 'docs'
          release: 'patch'
        - scope: 'deps-dev'
          release: false
  - - '@semantic-release/release-notes-generator'
    - preset: 'conventionalcommits'
  - - '@semantic-release/changelog'
    - changelogFile: 'CHANGELOG.md'
  - '@semantic-release/npm'
  - - '@semantic-release/git'
    - assets:
      - 'CHANGELOG.md'
      - 'package.json'
      message: 'chore(release): ${nextRelease.version}'
  - '@semantic-release/github'
