name: Benchmark

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up pnpm
        run: corepack enable

      - name: Set up Node.js with ${{ matrix.node-version }} version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run benchmark tests
        uses: CodSpeedHQ/action@v2
        with:
          run: pnpm vitest bench --run
          token: ${{ secrets.CODSPEED_TOKEN }}
